# Use root/example as user/password credentials
version: "3.1"

services:
    mongo:
        image: mongo
        container_name: oauth-db-dev
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456